#! /bin/bash

### Relay ###

# Create a schema.grapqhl if we don't have one
# if [ ! -e config/graphql/schema.graphql ]; then
#  babel-node ./scripts/update-schema.js
# fi

# Update schema every compile.. Remove for prod and do above conditional logic!
babel-node ./scripts/update-schema.js

# Run the relay compiler using the schema.graphql
relay-compiler --src ./src --schema config/graphql/schema.graphql


### Build ###

# Remove unnecessary files
rm -rf hash.json build.json public/assets

# Create a new public/assets directory
mkdir public/assets

# Build webpack bundle
if [ $NODE_ENV == "production" ]; then
  node node_modules/webpack/bin/webpack --config ./config/webpack.production.config.js --json > config/build.json
else
  node node_modules/webpack/bin/webpack --config ./config/webpack.development.config.js --json > config/build.json
fi

# Build the hash.json file
node scripts/build-hash

# Run the app on babel for ES6 support
babel-node ./app.js